// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RAD302Week3Lab12026CL.S00198790;

#nullable disable

namespace RAD302Week3Lab12026CL.S00198790.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260311172952_Seed Customer Data")]
    partial class SeedCustomerData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RAD302Week3Lab12026CL.S00198790.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Galway",
                            CreditRating = 700m,
                            Name = "John Murphy"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Dublin",
                            CreditRating = 650m,
                            Name = "Mary Kelly"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Cork",
                            CreditRating = 720m,
                            Name = "Tom O'Brien"
                        },
                        new
                        {
                            ID = 4,
                            Address = "Limerick",
                            CreditRating = 680m,
                            Name = "Sarah Walsh"
                        },
                        new
                        {
                            ID = 5,
                            Address = "Waterford",
                            CreditRating = 710m,
                            Name = "David Ryan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
